spring:
  profiles:
    active: dev

mybatis:
  typeAliasesPackage: com.ha.demo.entity
  mapperLocations: classpath:mapper/*.xml


---
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC
    username: root
    password: huhao123
    driver-class-name: com.mysql.cj.jdbc.Driver
